---
- name: Lock versions
  shell: >
    sudo yum versionlock add kubectl kubelet kubeadm kubernetes-cni docker

- name: Create kubelet service directory
  file: path=/etc/systemd/system/kubelet.service.d state=directory
  register: kubelet_service_dir
  ignore_errors: True

- name: Template kubeadm
  template:
    src: 10-kubeadm.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  when:
    - inventory_hostname in groups['master']

- name: detect docker's cgroup-driver
  shell: docker info 2>/dev/null |grep -i cgroup | cut -d":" -f2 | tr -d " "
  register: docker_cgroup_driver

- replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '--cgroup-driver=(systemd|cgroupfs)'
    replace: '--cgroup-driver={{docker_cgroup_driver.stdout}}'
    backup: no
  when:
    - inventory_hostname in groups['master']

- name: Reload systemd units after changing 10-kubeadm.conf
  command: systemctl daemon-reload

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - docker
    - kubelet

- name: Set kubectl completion bash
  shell: |
    alias k=kubectl
    complete -F __start_kubectl k
  args:
    executable: /bin/bash


